version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.11

    working_directory: /go/src/github.com/hashicorp/vault-plugin-database-elasticsearch

    steps:
    - checkout

    - run:
        name: "Install Dep"
        command: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

    - run:
        name: "Install Dependencies"
        command: dep ensure

    - run:
        name: "Run Tests"
        command: go test -v

    - run:
        name: "Install Gox"
        command: go get github.com/mitchellh/gox

    - run:
        name: "Run Build"
        command: ./scripts/build.s